### ISSUE TITLE
Logged in as different names in different languages

### ISSUE THREAD

**Issue by spaasis** [vrk-kpa/opendata#748] opened 2019-10-18 10:50 UTC
Hi,
This is a weird one.
When I log in, in the top right corner of the site it shows a different name based on my language selection. If I click on the name, it takes me to my account as it should, just the display is wrong.
In Swedish it showed my username correctly, but it showed my username to my colleague as well.. :)

**Comment by Zharktas** [comment] 2019-10-18 10:53
Hello,

this is known caching issue which we hopefully fix soon, it is not as critical since the profile link itself is always the same and redirects to the correct profile.

**Comment by eetumans** [comment] 2019-11-07 10:36
@spaasis We did not manage to reproduce this internally but we are well aware that this was happening to several people, presumably due to caching. This should be hopefully fixed in [release 3.18.0](https://github.com/vrk-kpa/opendata/releases/tag/v3.18.0). I'll close the issue but if you do verify that the issue persists feel free to reopen this and we'll look into it further.

**Closed by eetumans** 2019-11-07 10:36 UTC
